// SIDEBAR DISPLAY CONSTANTS
export const SIDEBAR_NAVIGATION = 'SIDEBAR_NAVIGATION';
export const SIDEBAR_LOGIN = 'SIDEBAR_LOGIN';

// MENU DISPLAY CONSTANTS
export const MESSAGES_MENU = 'MESSAGES_MENU';
export const PROFILE_MENU = 'PROFILE_MENU';
export const NO_MENU = 'NO_MENU';
