// SIDEBAR DISPLAY CONSTANTS
export const SIDEBAR_NAVIGATION = 'SIDEBAR_NAVIGATION';
export const SIDEBAR_LOGIN = 'SIDEBAR_LOGIN';
export const SIDEBAR_MESSAGES = 'SIDEBAR_MESSAGES';
export const SIDEBAR_AUTH_TYPE_LOGIN = 'SIDEBAR_AUTH_TYPE_LOGIN';
export const SIDEBAR_AUTH_TYPE_SIGNUP = 'SIDEBAR_AUTH_TYPE_SIGNUP';
