/**
 * @description application constants for conditional rendering.
 */

// SIDEBAR DISPLAY CONSTANTS
export const SIDEBAR_NAVIGATION = 'SIDEBAR_NAVIGATION';
export const SIDEBAR_AUTH = 'SIDEBAR_AUTH';
export const SIDEBAR_AUTH_TYPE_LOGIN = 'SIDEBAR_AUTH_TYPE_LOGIN';
export const SIDEBAR_AUTH_TYPE_SIGNUP = 'SIDEBAR_AUTH_TYPE_SIGNUP';
export const SIDEBAR_MESSAGES = 'SIDEBAR_MESSAGES';
export const SIDEBAR_FEED = 'SIDEBAR_FEED';

// ENCHANT CONSTANTS
export const ENCHANT_SEARCH_TYPE_POPULAR = 'ENCHANT_SEARCH_TYPE_POPULAR';
export const ENCHANT_SEARCH_TYPE_NEW = 'ENCHANT_SEARCH_TYPE_NEW';
export const ENCHANT_SEARCH_TYPE_FRIEND = 'ENCHANT_SEARCH_TYPE_FRIEND';
