/**
 * @description application constants for conditional rendering.
 */

// SIDEBAR DISPLAY CONSTANTS
// sidebar type
export const SIDEBAR_NAVIGATION = 'SIDEBAR_NAVIGATION';
// sidebar type
export const SIDEBAR_AUTH = 'SIDEBAR_AUTH';
// sidebar sub types
export const SIDEBAR_AUTH_TYPE_LOGIN = 'SIDEBAR_AUTH_TYPE_LOGIN';
export const SIDEBAR_AUTH_TYPE_SIGNUP = 'SIDEBAR_AUTH_TYPE_SIGNUP';
//sidebar type
export const SIDEBAR_MESSAGES = 'SIDEBAR_MESSAGES';
// sidebar type
export const SIDEBAR_FEED = 'SIDEBAR_FEED';

// SWELL MENU SPECIFIC
export const SIDEBAR_SWELL_MENU_SEARCH = 'SIDEBAR_SWELL_MENU_SEARCH';
export const SIDEBAR_SWELL_MENU_ENCHANT_CATEGORY =
  'SIDEBAR_SWELL_MENU_ENCHANT_CATEGORY';

// ENCHANT CONSTANTS
export const ENCHANT_SEARCH_TYPE_POPULAR = 'ENCHANT_SEARCH_TYPE_POPULAR';
export const ENCHANT_SEARCH_TYPE_NEW = 'ENCHANT_SEARCH_TYPE_NEW';
export const ENCHANT_SEARCH_TYPE_FRIEND = 'ENCHANT_SEARCH_TYPE_FRIEND';
